### ISSUE TITLE
entrypoint.sh missing

### ISSUE THREAD

**Issue by gwong-astro** [singularityhub/mongo#2]
I have just tried to follow the instructions on the landing page, I was not able to find the directory docker (I am assuming the page is out of date).  However, when I was able to build the container I hit an issue when trying to the command "./mongo.img --help" I get a message stating that entrypoint.sh not found.  Any solutions around this?  This is running on Ubuntu 19.1 with Singularity version 3.4

**Comment by vsoch** [comment]
This was last updated almost 3 years ago, so yes it’s out of date! I’ll take a look and update tomorrow.

**Comment by vsoch** [comment]
All set @gwong-astro - check out the readme for fixed up instructions.
